website/routes.py
from .models import User, Carro, Foto
from flask import render_template, Blueprint, redirect, url_for, flash
from .forms import LoginForm, RegisterForm, CarForm, AlugarForm, DevolverForm, CarEditForm, DeletarForm, EditUserForm, CarImgForm
from . import db
from flask_login import login_user, current_user, logout_user, login_required

routes = Blueprint('routes', __name__)


@routes.route('/')
def home():
    return render_template('home.html', current_user=current_user)


@routes.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        attempted_user = User.query.filter_by(nome=form.nome.data).first()
        if attempted_user and attempted_user.check_password_correction(
          attempted_password = form.password.data
        ):
            login_user(attempted_user)
            flash(f'Bem-vindo(a), {attempted_user.nome}!', category='success')
            return redirect(url_for('routes.home'))
        else:
            flash('Nome ou senha errados!', category='danger')

    return render_template('login.html', form=form, current_user=current_user)


@routes.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('Desconectado com sucesso, volte sempre!', category='success')
    return redirect(url_for('routes.home'))


@routes.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user_to_create = User(
            nome=form.nome.data,
            identidade=form.identidade.data,
            carteira_motorista=form.carteira_motorista.data,
            telefone=form.telefone.data,
            email=form.email.data,
            password=form.password1.data,
            endereco=form.endereco.data,
        )
        db.session.add(user_to_create)
        db.session.commit()

        login_user(user_to_create)
        flash(f"Cadastrado com sucesso! Bem-vindo(a), {user_to_create.nome}!", category='success')
        return redirect(url_for('routes.home'))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f'Erro ao cadastrar: {err_msg}', category='danger')

    return render_template('register.html', form=form, current_user=current_user)


@routes.route('/car-register', methods=['GET', 'POST'])
@login_required
def car_register():
    if current_user.role == 'manager':
        form = CarForm()
        if form.validate_on_submit():
            car_to_add = Carro(
                nome=form.nome.data,
                marca=form.marca.data,
                ano_fabricacao=form.ano_fabricacao.data,
                consumo=form.consumo.data,
                preco_base=form.preco_base.data,
                descricao=form.descricao.data,

            )
            db.session.add(car_to_add)
            db.session.commit()

            flash(f'Veículo cadastrado com sucesso!', category='success')
            return redirect(url_for('routes.car_register'))
        if form.errors != {}:
            for err_msg in form.errors.values():
                flash(f'Erro ao cadastrar: {err_msg}', category='danger')

        return render_template('car-register.html', form=form, current_user=current_user)

    else:
        flash('Esta página é apenas para administradores!', category='danger')
        return redirect(url_for('routes.home'))


@routes.route('/catalogo', methods=['GET', 'POST'])
def catalogo():
    carros = Carro.query.filter_by(locador=None)
    return render_template('catalogo.html', carros=carros, current_user=current_user)


@routes.route('/processamento/<carro_id>', methods=['GET', 'POST'])
@login_required
def processamento(carro_id):
    carro_alugado = Carro.query.get_or_404(carro_id)

    form = AlugarForm()
    if form.validate_on_submit():
        carro_alugado.locador = current_user.id
        db.session.commit()
        flash(f'Alugado com sucesso! {carro_alugado.nome} está te aguardando na concessionária!', category='success')
        return redirect(url_for('routes.home'))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f'Erro ao concluir aluguel: { err_msg }', category='danger')

    return render_template('processamento.html', carro=carro_alugado, current_user=current_user, form=form)


@routes.route('/car-info/<carro_id>', methods=['GET', 'POST'])
def car_info(carro_id):
    carro = Carro.query.get_or_404(carro_id)
    imagens = []
    for imagem in carro.imagem:
        imagens.append(imagem)
    imagens_json = [{'id': foto.id, 'link': foto.link} for foto in imagens]

    return render_template('car-info.html', current_user=current_user, carro=carro, imagens=imagens_json)


@routes.route('/caros_alugados', methods=['GET', 'POST'])
@login_required
def carros_alugados():
    carros_alugados = Carro.query.filter_by(locador=current_user.id)
    carros = []
    for carro in carros_alugados:
        carros.append(carro)
    return render_template('carros_alugados.html', carros=carros, current_user=current_user)


@routes.route('/devolucao/<carro_id>', methods=['GET', 'POST'])
@login_required
def devolucao(carro_id):
    carro = Carro.query.get_or_404(carro_id)
    form = DevolverForm()
    if form.validate_on_submit():
        carro.locador = None
        db.session.commit()
        flash('Devolução feita com sucesso! Iremos buscar o que é nosso.', category='success')
        return redirect(url_for('routes.home'))

    return render_template('devolucao.html', carro=carro, form=form, current_user=current_user)


@routes.route('/edicao', methods=['GET', 'POST'])
@login_required
def edicao():
    carros = Carro.query.all()
    return render_template('edicao.html', carros=carros, current_user=current_user)


@routes.route('/edicao_carro/<carro_id>', methods=['GET', 'POST'])
@login_required
def edicao_carro(carro_id):
    if current_user.role == 'manager':
        carro = Carro.query.get_or_404(carro_id)

        form = CarEditForm(obj=carro)
        if form.validate_on_submit():

            carro.nome=form.nome.data
            carro.marca=form.marca.data
            carro.ano_fabricacao=form.ano_fabricacao.data
            carro.consumo=form.consumo.data
            carro.preco_base=form.preco_base.data
            carro.descricao=form.descricao.data

            db.session.commit()

            flash(f'Veículo editado com sucesso!', category='success')

            return redirect(url_for('routes.edicao'))

        if form.errors != {}:
            for err_msg in form.errors.values():
                flash(f'Erro ao editar: {err_msg}', category='danger')

        return render_template('edicao_carro.html', form=form, current_user=current_user, carro=carro)

    else:
        flash('Esta página é apenas para administradores!', category='danger')
        return redirect(url_for('routes.home'))


@routes.route('/delecao_carro/<carro_id>', methods=['GET', 'POST'])
@login_required
def delecao_carro(carro_id):
    if current_user.role == 'manager':
        carro = Carro.query.get_or_404(carro_id)
        form = DeletarForm()
        if form.validate_on_submit():
            db.session.delete(carro)
            db.session.commit()
            flash('O carro foi deletado!', category='success')
            return redirect(url_for('routes.home'))

        return render_template('delecao_carro.html', carro=carro, form=form, current_user=current_user)
    else:
        flash('Esta página é apenas para administradores!', category='danger')
        return redirect(url_for('routes.home'))


@routes.route('/edicao_perfil', methods=['GET', 'POST'])
@login_required
def edicao_perfil():
    form = EditUserForm(obj=current_user, current_user=current_user)
    if form.validate_on_submit():
        current_user.nome=form.nome.data
        current_user.identidade=form.identidade.data
        current_user.carteira_motorista=form.carteira_motorista.data
        current_user.telefone=form.telefone.data
        current_user.email=form.email.data
        current_user.endereco=form.endereco.data
        current_user.senha=form.password1.data

        db.session.commit()
        flash('Perfil alterado com sucesso!', category='success')
        return redirect(url_for('routes.home'))

    if form.errors != {}:
        for err_msg in form.errors.values():
            flash(f'Erro ao editar: {err_msg}', category='danger')

    return render_template('edit_profile.html', current_user=current_user, form=form)


@routes.route('/delecao_perfil', methods=['GET', 'POST'])
@login_required
def delecao_perfil():
    if current_user.role == 'client':
        form = DeletarForm()
        if form.validate_on_submit():

            carros = Carro.query.filter_by(locador=current_user.id)
            for carro in carros:
                carro.locador=None
                db.session.commit()

            db.session.delete(current_user)
            db.session.commit()
            flash('Conta deletada com sucesso! Faça outra quando quiser!', category='success')
            return redirect(url_for('routes.home'))

        if form.errors != {}:
            for err_msg in form.errors.values():
                flash(f'Erro ao deletar: {err_msg}', category='danger')

        return render_template('delete_user.html', current_user=current_user, form=form)
    else:
        flash('A conta de superusuário não pode ser apagada!', category='danger')
        return redirect(url_for('routes.home'))


@routes.route('/adicionar_imagem/<carro_id>', methods=['GET', 'POST'])
@login_required
def adicionar_imagem(carro_id):
    if current_user.role == 'manager':
        carro = Carro.query.get_or_404(carro_id)
        form = CarImgForm()
        if form.validate_on_submit():
            imagem = Foto(link=form.link.data, carro=carro.id)
            db.session.add(imagem)
            db.session.commit()
            flash("Imagem adicionada com sucesso!", category="success")

website/templates/ImgList.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/imgList.css">{% endblock %}
{% block title %}Lista de imagens{% endblock %}

{% block content %}
        {% if imagens == [] %}
            <h3>Este veículo não possui imagens</h3>
        {% else %}
                {% for img in carro.imagem %}
                <div class="carro-imagem-container">
                    <img src="{{ img.link }}" alt="Imagem de carro">
                    <a class="btn btn-danger" href="{{ url_for('routes.delete_img', img_id=img.id, carro_id=carro.id) }}">Deletar imagem</a>
                </div>
                {% endfor %}
        {% endif %}

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <link type="image/png" sizes="16x16" rel="icon" href="https://img.icons8.com/?size=256&id=17577&format=png">

    <link rel="stylesheet" href="../static/base.css">

    {% block style %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark">
        <a class="navbar-brand" href="/">Início</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ">
              <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('routes.catalogo') }}">Ver catálogo</a>
              </li>
          </ul>
            {% if current_user.role == 'manager' %}
                <ul class="navbar-nav">
                    <li>
                        <a class="nav-link" href="{{ url_for('routes.logout') }}">Sair</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ url_for('routes.car_register') }}">Registrar Veículo</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ url_for('routes.carros_alugados') }}">Carros alugados</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ url_for('routes.edicao') }}">Editar carros</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ url_for('routes.edicao_perfil') }}">Editar perfil</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{ url_for('routes.deletar_usuario') }}">Deletar usuário</a>
                    </li>
                </ul>
            {% elif current_user.is_authenticated %}
                <ul class="navbar-nav">
                      <li>
                          <a class="nav-link" href="{{ url_for('routes.logout') }}">Sair</a>
                      </li>
                      <li>
                          <a class="nav-link" href="{{ url_for('routes.carros_alugados') }}">Carros alugados</a>
                      </li>
                       <li>
                        <a class="nav-link" href="{{ url_for('routes.edicao_perfil') }}">Editar perfil</a>
                      </li>
                </ul>
            {% else %}
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('routes.login') }}">Login</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('routes.register') }}">Registrar-se</a>
                  </li>
              </ul>
            {% endif %}
  
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                  <button type="button" style="background-color:transparent; border:none;" class="btn-close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  {{ message }}
              </div>
          {% endfor %}
      {% endif %}
  {% endwith %}
{% block content %} {% endblock %}

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

website/templates/car-info.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/car_info.css">{% endblock %}
{% block title %}Sobre{% endblock %}

{% block content %}
    <div class="container">
        <h1>Sobre o {{ carro.nome }}</h1>
        {% if imagens != [] %}
            <div class="carrossel-gambiarra">
                <button class="btn btn-primary" onclick="anterior()">Anterior</button>
                <img id="imagemCarrossel" src="{{ imagens[0].link }}">
                <button class="btn btn-primary" onclick="proximo()">Próximo</button>
            </div>
        {% endif %}
        <p>{{ carro.descricao }}</p>
        <p>Marca: {{ carro.marca }}</p>
        <p>Ano de fabricação: {{ carro.ano_fabricacao }}</p>
        <p>Consumo (km/l misto): {{ carro.consumo }}</p>
        <div class="buttons">
            {% if carro.locador == None %}
                <a class="btn btn-outline btn-success" href="{{ url_for('routes.processamento', carro_id=carro.id) }}">Alugar</a>
            {% endif %}
            <a class="btn btn-outline btn-secondary" href="{{ url_for('routes.catalogo') }}">Voltar</a>
        </div>

    </div>

<script>
    var imagens = {{ imagens | tojson }};
    var indiceAtual = 0;

    function mostrarImagem(indice) {
        document.getElementById("imagemCarrossel").src = imagens[indice].link;
    }

    function proximo() {
        indiceAtual = (indiceAtual + 1) % imagens.length;
        mostrarImagem(indiceAtual);
    }

    function anterior() {
        indiceAtual = (indiceAtual - 1 + imagens.length) % imagens.length;
        mostrarImagem(indiceAtual);
    }
</script>
{% endblock %}

website/templates/carros_alugados.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/catalogo.css">{% endblock %}
{% block title %}Seus carros{% endblock %}
{% block content %}
    <h2 style="margin:24px 0px; text-align:center; text-transform:uppercase;">Veículos alugados por {{ current_user.nome }}</h2>
    <div class="products-container">
        {% if carros == [] %}
            <h2>Você ainda não tem carros alugados! Para alugar um carro, basta ir ao catálogo e fazer a sua escolha.</h2>
        {% else %}
            {% for carro in carros %}
                <div class="product-container">
                    {% if carro.imagem[0] %}<img src="{{ carro.imagem[0].link }}" alt="imagem do carro"/>{% endif %}
                    <h3>{{ carro.nome }}</h3>
                    <p>{{ carro.descricao }}</p>

                    <div class="buttons">
                        <a class="btn btn-outline btn-info" href="{{ url_for('routes.car_info', carro_id=carro.id) }}">Ver mais</a>
                        <a class="btn btn-outline btn-info" href="{{ url_for('routes.devolucao', carro_id=carro.id) }}">Devolver</a>
                    </div>

                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

website/templates/catalogo.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/catalogo.css">{% endblock %}
{% block title %}Catálogo{% endblock %}
{% block content %}
    <h2>Veículos disponíveis</h2>
    <div class="products-container">
        {% for carro in carros %}
        <div class="product-container">
            {% if carro.imagem[0] %}<img src="{{ carro.imagem[0].link }}" alt="imagem do carro"/>{% endif %}
            <h3>{{ carro.nome }}</h3>
            <p>{{ carro.descricao }}</p>
            <p>Preço base: <span class="price">R${{ carro.preco_base }}</span></p>

            <div class="buttons">
                <a class="btn btn-outline btn-info" href="{{ url_for('routes.car_info', carro_id=carro.id) }}">Ver mais</a>
                <a class="btn btn-outline btn-success" href="{{ url_for('routes.processamento', carro_id=carro.id) }}">Alugar</a>
            </div>

        </div>
        {% endfor %}
    </div>

{% endblock %}

website/templates/delecao_carro.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/confirmacoes.css">{% endblock %}
{% block title %}Deletar veículo{% endblock %}
{% block content %}
    <div class="confirmation-container">
        <h1>Confirmar deleção</h1>
        <p>Você está prestes a deletar {{ carro.marca }} {{ carro.nome }}. Ao clicar em Deletar, você confirmará a exclusão do veículo da base de dados, o processo não poderá ser desfeito. </p>
        <form method="post" class="form-register">
            {{ form.hidden_tag() }}
            <a class="btn btn-secondary btn-lg" href="{{ url_for('routes.edicao') }}">Cancelar deleção</a>
            {{ form.submit(class='btn btn-danger btn-lg') }}
        </form>
    </div>

{% endblock %}

website/templates/deletar_usuario.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/deletar_usuarios.css">{% endblock %}
{% block title %}Deletar usuário{% endblock %}
{% block content %}
    <div class="deletar-usuarios-container">
        <h1>Deletar usuários</h1>
        <p>Algum usuário não entra há muito tempo? Pediu para remover a conta do sistema pois perdeu a senha? Isso pode ser feito por aqui</p>
        {% for usuario in users %}
            <div class="user-text">
                <p>{{usuario.nome}}</p><a href="{{ url_for('routes.apagar_usuario', user_id=usuario.id) }}">Deletar</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

website/templates/delete_user.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/confirmacoes.css">{% endblock %}
{% block title %}Deletar veículo{% endblock %}
{% block content %}
    <div class="confirmation-container">
        <h1>Confirmar deleção</h1>
        <p>Você está prestes a deletar sua própria conta. Ao clicar em deletar, sua conta será perdida para sempre e todos os carros atualmente alugados por você serão buscados pela locadora de imediato, conforme previsto no contrato.</p>
        <form method="post" class="form-register">
            {{ form.hidden_tag() }}
            <a class="btn btn-secondary btn-lg" href="{{ url_for('routes.home') }}">Cancelar deleção</a>
            {{ form.submit(class='btn btn-danger btn-lg') }}
        </form>
    </div>
{% endblock %}

website/templates/edicao.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/edit.css">{% endblock %}

{% block title %}Edição{% endblock %}
{% block content %}
    <h2 style="margin:24px 0px; text-align:center; text-transform:uppercase;">Edição de veículos</h2>
    <div class="products-container">
        {% for carro in carros %}
        <div class="product-container">
            <h3>{{ carro.nome }}</h3>
            {% if carro.imagem[0] %}<img src="{{ carro.imagem[0].link }}" alt="imagem do carro"/>{% endif %}
            <p>Marca: {{ carro.marca }}</p>
            <p>Ano: {{ carro.ano_fabricacao }}</p>
            <p>Consumo (km/l): {{ carro.consumo }}</p>
            <p>Preço base: {{ carro.preco_base }}</p>
            <div class="buttons">
                <a class="btn btn-outline btn-danger" href="{{ url_for('routes.delecao_carro', carro_id=carro.id) }}">Deletar</a>
                <a class="btn btn-outline btn-info" href="{{ url_for('routes.edicao_carro', carro_id=carro.id) }}">Editar</a>
                <a class="btn btn-outline btn-info" href="{{ url_for('routes.adicionar_imagem', carro_id=carro.id) }}">Adicionar imagem</a>
                <a class="btn btn-outline btn-info" href="{{ url_for('routes.deletar_imagem', carro_id=carro.id) }}">Deletar imagem</a>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

website/templates/edicao_carro.html
{% extends 'base.html' %}

{% block title %}Editar veículo{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" class="form-register">
            {{ form.hidden_tag() }}
            <h1>Editar veículo</h1>
            {{ form.nome.label() }}
            {{ form.nome(class='form-control') }}

            {{ form.marca.label() }}
            {{ form.marca(class='form-control') }}

            {{ form.ano_fabricacao.label() }}
            {{ form.ano_fabricacao(class='form-control') }}

            {{ form.consumo.label() }}
            {{ form.consumo(class='form-control') }}

            {{ form.preco_base.label() }}
            {{ form.preco_base(class='form-control') }}

            {{ form.descricao.label() }}
            {{ form.descricao(class='form-control', placeholder='Qualidades do carro (opcional)') }}


            {{ form.submit(class='btn btn-primary btn-lg btn-block') }}
        </form>
    </div>

    <style>
        .form-control { margin-bottom:24px; }
        .btn btn-primary { margin: auto; }
        h1 { text-align:center; margin-top:12px; }
    </style>
{% endblock %}

website/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %}Editar Perfil{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST" class="form-register">
            {{ form.hidden_tag() }}

            <h1>Editar Perfil</h1>

            {{ form.nome.label() }}
            {{ form.nome(class='form-control') }}

            {{ form.identidade.label() }}
            {{ form.identidade(class='form-control')}}

            {{ form.carteira_motorista.label() }}
            {{ form.carteira_motorista(class_='form-control')}}

            {{ form.telefone.label() }}
            {{ form.telefone(class='form-control')}}

            {{ form.email.label() }}
            {{ form.email(class='form-control')}}

            {{ form.endereco.label() }}
            {{ form.endereco(class='form-control')}}

            {{ form.password1.label() }}
            {{ form.password1(class="form-control") }}

            {{ form.password2.label() }}
            {{ form.password2(class="form-control") }}

            {{ form.submit(class="btn btn-primary btn-lg btn-block ") }}
            {% if current_user.role == 'client' %}
                <a href="{{ url_for('routes.delecao_perfil') }}" class="btn btn-danger btn-lg btn-block ">Deletar Perfil</a>
            {% endif %}
        </form>
    </div>
    <style>
        .form-control { margin-bottom:24px; }
        .btn btn-primary{ margin: auto; }
        a{ margin-bottom: 30px; }
        h1 { text-align:center; margin-top:12px; }
    </style>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block style %}<link rel="stylesheet" href="../static/home.css">{% endblock %}
{% block title %}Locadora{% endblock %}

{% block content %}
    <div class="container">
        <h1>Locadora de veículos HS</h1>
        <p>Alugue o veículo dos seus sonhos hoje mesmo por um preço acessível!</p>
        <a class="btn btn-primary"  href="{{ url_for('routes.catalogo') }}" >Veículos disponíveis</a>
    </div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" class="form-register">
            {{ form.hidden_tag() }}
            <h1>Login</h1>
            {{ form.nome.label() }}
            {{ form.nome(class='form-control', placeholder='Usuário') }}
            {{ form.password.label() }}
            {{ form.password(class='form-control', placeholder='senha') }}
            {{ form.submit(class='btn btn-primary btn-lg btn-block') }}

        <div class="checkbox mb-3" style="text-align:center; margin-top:24px">
            <h6>Não tem uma conta?</h6>
            <a class="btn btn-sm btn-secondary" href="{{ url_for('routes.register') }}">Registrar</a>
        </div>

        </form>
    </div>

    <style>
        .form-control { margin-bottom:24px; }
        .btn btn-primary { margin: auto; }
        h1 { text-align:center; margin-top:12px; }
    </style>
{% endblock %}

website/templates/register.html
{% extends 'base.html' %}

{% block title %}Registrar-se{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST" class="form-register">
            {{ form.hidden_tag() }}

            <h1>Registrar conta</h1>

            {{ form.nome.label() }}
            {{ form.nome(class='form-control', placeholder='Usuário') }}

            {{ form.identidade.label() }}
            {{ form.identidade(class='form-control', placeholder='Identidade (RG/CPF/OAB)')}}

            {{ form.carteira_motorista.label() }}
            {{ form.carteira_motorista(class_='form-control', placeholder='Número da CNH')}}

            {{ form.telefone.label() }}
            {{ form.telefone(class='form-control', placeholder='Número do telefone')}}

            {{ form.email.label() }}
            {{ form.email(class='form-control', placeholder='Email')}}

            {{ form.endereco.label() }}
            {{ form.endereco(class='form-control', placeholder='Nome')}}

            {{ form.password1.label() }}
            {{ form.password1(class="form-control", placeholder="Senha") }}

            {{ form.password2.label() }}
            {{ form.password2(class="form-control", placeholder="Confirmar senha") }}

            {{ form.submit(class="btn btn-primary btn-lg btn-block ") }}

            <div class="checkbox mb-3" style="text-align:center; margin-top:24px">
                <h6>Já tem uma conta?</h6>
                <a class="btn btn-sm btn-secondary" href="{{ url_for('routes.login') }}">Entrar</a>
            </div>

        </form>
    </div>
    <style>
        .form-control { margin-bottom:24px; }
        .btn btn-primary { margin: auto; }
        h1 { text-align:center; margin-top:12px; }
    </style>
{% endblock %}